name: Push to S3

on:
  push:
    branches:
      - dev
      - main
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Minify JS Files
      run: npm run minify

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Check Branch Name
      run: echo "Branch name is -- ${{ github.ref }}"
      id: branch_check

    - name: Sync files to S3 on Main branch
      if: github.ref == 'refs/heads/main'
      run: aws s3 sync "${{ github.workspace }}/src" s3://iomd-nodeappfiles-bucket/prod
      
    - name: Sync files to S3 on Dev branch
      if: github.ref == 'refs/heads/dev'
      run: aws s3 sync "${{ github.workspace }}/src" s3://iomd-nodeappfiles-bucket/dev

    - name: Sync files to S3 on Qa branch
      if: github.ref == 'refs/heads/qa'
      run: aws s3 sync "${{ github.workspace }}/src" s3://iomd-nodeappfiles-bucket/qa

    - name: Create CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id E2PEL6DQT55P7S --paths "/*"
